---
- name: Discover latest version
  ansible.builtin.set_fact:
    pgbouncer_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/prometheus-community/pgbouncer_exporter/releases/latest',
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: pgbouncer_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - pgbouncer_exporter_version == "latest"
    - pgbouncer_exporter_binary_local_dir | length == 0
    - not pgbouncer_exporter_skip_install

- name: Get pgbouncer_exporter binary checksum
  when:
    - pgbouncer_exporter_binary_local_dir | length == 0
    - not pgbouncer_exporter_skip_install
  block:
    - name: Get checksum list from github
      ansible.builtin.set_fact:
        __pgbouncer_exporter_checksums: "{{ lookup('url', pgbouncer_exporter_checksums_url, wantlist=True) | list }}"
      run_once: true
      until: __pgbouncer_exporter_checksums is search('linux-' + pgbouncer_exporter_arch + '.tar.gz')
      retries: 10

    - name: "Get checksum for {{ pgbouncer_exporter_arch }}"
      ansible.builtin.set_fact:
        __pgbouncer_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __pgbouncer_exporter_checksums }}"
      when:
        - "('linux-' + pgbouncer_exporter_arch  + '.tar.gz') in item"

- name: Set pgbouncer_exporter_download_url
  set_fact:
    pgbouncer_exporter_download_url: "https://github.com/prometheus-community/pgbouncer_exporter/releases/download/v{{ pgbouncer_exporter_version }}/pgbouncer_exporter-{{ pgbouncer_exporter_version }}.linux-{{ pgbouncer_exporter_arch }}.tar.gz"