---
- name: Determine latest GitHub release (local)
  delegate_to: localhost
  become: false
  uri:
    url: "https://api.github.com/repos/prometheus-community/pgbouncer_exporter/releases/latest"
    body_format: json
  register: _github_release
  until: _github_release.status == 200
  retries: 5

- name: Set pgbouncer_exporter_version
  set_fact:
    pgbouncer_exporter_version: "{{ _github_release.json.tag_name
      | regex_replace('^v?([0-9\\.]+)$', '\\1') }}"

- name: Set pgbouncer_exporter_download_url
  set_fact:
    pgbouncer_exporter_download_url: "https://github.com/prometheus-community/pgbouncer_exporter/releases/download/v{{ pgbouncer_exporter_version }}/pgbouncer_exporter-{{ pgbouncer_exporter_version }}.linux-{{ pgbouncer_exporter_arch }}.tar.gz"
